{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "torale.fullname" . }}-api
  labels:
    {{- include "torale.api.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/neg-health-check: '{"http":{"port":{{ .Values.api.service.targetPort }},"request_path":"{{ .Values.api.readinessProbe.httpGet.path }}"}}'
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "torale.api.selectorLabels" . | nindent 4 }}
{{- end }}
