{{- if .Values.api.enabled -}}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "torale.fullname" . }}-api
  labels:
    {{- include "torale.api.labels" . | nindent 4 }}
spec:
  healthCheck:
    checkIntervalSec: 5
    port: {{ .Values.api.service.targetPort }}
    type: HTTP
    requestPath: {{ .Values.api.readinessProbe.httpGet.path }}
{{- end }}
{{- if .Values.frontend.enabled -}}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "torale.fullname" . }}-frontend
  labels:
    {{- include "torale.frontend.labels" . | nindent 4 }}
spec:
  healthCheck:
    checkIntervalSec: 5
    port: {{ .Values.frontend.service.targetPort }}
    type: HTTP
    requestPath: /
{{- end }}
{{- if .Values.docs.enabled -}}
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "torale.fullname" . }}-docs
  labels:
    {{- include "torale.labels" . | nindent 4 }}
    app.kubernetes.io/component: docs
spec:
  healthCheck:
    checkIntervalSec: 5
    port: {{ .Values.docs.service.targetPort | default 80 }}
    type: HTTP
    requestPath: /
{{- end }}
