{{- if and .Values.certificate.enabled .Values.ingress.tls.enabled -}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.certificate.name }}
  labels:
    {{- include "torale.labels" . | nindent 4 }}
spec:
  domains:
  - {{ .Values.domains.frontend }}
  - {{ .Values.domains.api }}
  {{- if .Values.docs.enabled }}
  - {{ .Values.domains.docs }}
  {{- end }}
{{- end }}
