{{- if and .Values.docs.enabled .Values.docs.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "torale.fullname" . }}-docs
  labels:
    {{- include "torale.labels" . | nindent 4 }}
    app.kubernetes.io/component: docs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "torale.fullname" . }}-docs
  minReplicas: {{ .Values.docs.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.docs.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.docs.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
