{{- if .Values.docs.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "torale.fullname" . }}-docs
  labels:
    {{- include "torale.labels" . | nindent 4 }}
    app.kubernetes.io/component: docs
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"{{ include "torale.fullname" . }}-docs"}}'
spec:
  type: {{ .Values.docs.service.type }}
  ports:
    - port: {{ .Values.docs.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "torale.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: docs
{{- end }}
