{{- if .Values.ingress.enabled -}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ssl-redirect
  labels:
    {{- include "torale.labels" . | nindent 4 }}
spec:
  redirectToHttps:
    enabled: true
{{- end }}
