{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "torale.fullname" . }}-frontend
  labels:
    {{- include "torale.frontend.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/neg-health-check: '{"http":{"port":{{ .Values.frontend.service.targetPort }},"request_path":"/"}}'
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "torale.frontend.selectorLabels" . | nindent 4 }}
{{- end }}
